---
title: Nüfus ve Açlık
author: 
  - Zeliha Aybike Taş[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080313, [Github Repo](https://github.com/zelihaaybike/arasinav)



# Giriş
  Malthus der ki “Nüfusun gücü, yeryüzünün, insanın geçimini sağlama gücüne kıyasla, sınırsız ölçüde büyüktür.” @article{meek1953malthus,} Buna karşın dünyanın nüfusu her geçen gün artmaktadır. Bununla birlikte artan nüfusun getirdiği sorunlar da artmaktadır. Dünyaya gelen her yeni insan, hali hazırda dünyada bulunan diğer insanlar gibi, yaşamını idame ettirmek için gerekli olan temel ihtiyaçlar dışında bazı lüks ihtiyaçlara da sahiptir. Bu ihtiyaçlar bazen çok büyük bazen çok küçük olabilse de tümünün karşılanması her ülkede eşit şekilde mümkün olmaktadır. Dünyaya gelen her insan, kendisinin bulunduğu ortamdan daha farklı imkanlara sahip olan, başka ortamlarda bulunan insanlarla aynı koşullarda olamamakla birlikte; olayları ve durumları değerlendiriş açısında  da farklılıklara sahiptir. Öyle ki benzer olay ve durumlara, kendisiyle aynı koşullara sahip olan fakat o koşulları avantaja çeviren kişilerle, aynı perspektiften bakamayabilir. Bu durumda onları suçlamak ne kadar doğrudur? İnsanların başarı veya başarısızlığında içinde bulunduğu koşul ve mekanın etkisi var mıdır? Dünya nüfusunun ne kadarı, kalan kısma göre daha avantajlı bir yaşam sürmektedir? 

## Çalışmanın Amacı
  Dünyadaki açlığın yıllara göre dağılımını ve bunun coğrafya ile ilişkisini incelemek. Bu konuyu nüfus, gelişmişlik düzeyi ve diğer etkenleri de hesaba katarak çözümleyip, konu hakkında neler yapılabileceği hakkında akıl yürütmek.

## Literatür 
  Dünyadaki tüm canlılar türünün devamlılığını sağlamak amacıyla üreme yeteneğine sahiptir. Canlıların birçoğu, hatta insan hariç tümü, üreme üzerinde bir kontrol sağlayamamaktadır. Bundan dolayı doğa bu görevi üstlenir. Çeşitli yollarla artan canlı nüfusunun azalmasına önayak olur. Bundan dolayı üreme konusunda en tembel canlılardan biri olan insan hariç, herhangi bir canlının popülasyonunun fazlalığı gibi ekosistemi tehdit eden bir durum ortaya çıkmamıştır. Fakat söylediğim tehdit durumu insan nüfusu için geçerlidir. İnsan iradesi sayesinde üreme konusunda bir kontrole sahip olmasına karşın nüfusu gün geçtikçe daha çok artmaktadır. 
 
  Bu artış kirlilik, artan suçlar, işsizlik vb. birçok sorunu ortaya çıkarmaktadır.  Şüphesiz bu sorunlardan en büyüğü ve ciddisi ise yoksulluktur. “Dünya nüfusunun % 46’sı yani 2.800.000.000 insan, Dünya Bankası tarafından tespit edilen günlük 2 ABD doları olan, yoksulluk sınırının altında yaşamaktadır. 1.200.000.000 insan ise günlük 1 ABD doları olan açlık sınırının altında yaşamaya çalışmaktadır.”@inproceedings{tacs2012turkiye} Bu oranlara bakıldığında dünyanın yaklaşık olarak yarısının açlık tehlikesi ile karşı karşıya olduğu görülmektedir. Peki bunun nedeni dünyada yeteri kadar yiyecek olmamasından mı kaynaklıdır. Buna cevap olarak şu anlık net bir şekilde hayır denebilir. Dünyadaki toprakların yaklaşık %37’si yiyecek için kullanılmaktadır. Bu toprakların da çoğu Kuzey Amerika, Asya ve Doğu Avrupa’dadır. Bu bilgilere göre açlığın genelde Afrika kıtasında ve Ortadoğu’da yer aldığını düşünürsek, diğer bölgelerde üretilen yiyeceklerin bu bölgelere dağılımı gerekmektedir. Çünkü özellikle Afrika zaten aşın nüfuslanmayla mücadele etmektedir. Aşın nüfuslanma ise; herhangi bir ülke veya bölgede harekete geçirilebilmiş olan kaynakların orada yaşamakta olan nüfusa yetmemesi sonucu ekonomik ve sosyal bazı sorunların yaşanması durumuna denir. Bu sorunlardan biri de elbette ki esas konumuz olan açlıktır.
  
  Yiyeceğin yeterli üretimi hakkında yönelttiğim soruya, şu anlık hayır gibi bir cevap vermemin nedenine gelecek olursak çıkış yolumuz Malthus olur. Çünkü şu an dünyada üretilen gıda tüm dünyaya yetebilecek olmasına karşın, dağılımının olmaması sebebiyle israf edilmektedir. Fakat gelecekte konu dağılım değil, üretim olabilir çünkü Malthus der ki; “Nüfus, kısıtlanmadığında, geometrik oranla çoğalır. Geçim araçları ise, ancak aritmetik oranla artar…”@article{meek1953malthus,} Dolayısıyla insan nüfusu katlanarak artarken, gıda ise aritmetik bir şekilde artar. Bu durum ise halihazırda açlığın zaten yoğun olduğu dünyamız için, gelecekte daha büyük sıkıntıların ortaya çıkacağı yönündedir.
  
  Sonuç olarak dünyadaki açlık zaten yeterli değilmiş gibi gelecekte, popülasyonun artışıyla birlikte, bu sorunun daha da büyüyeceği yadsınamaz bir gerçektir. Şu anki açlığı bitirmeden de gelecek için önlem almanın elle tutulur bir yararının olmayacağı gibi, şu anki açlığı bitirmek için yapılan çalışmaları da sistematikleştirmek gerekmektedir. 




**_Taslakta bu cümleden sonra yer alan hiçbir şey silinmemelidir._**

\newpage
# Kaynakça {#references}
<div id="refs"></div>
https://dergipark.org.tr/en/pub/baunsobed/issue/50339/651864

https://www.researchgate.net/profile/Irfan-Kaygalak/publication/355370414_Cografya_Kaderdir_Uzerine_On_the_Geography_is_Destiny_Oz/links/616d56bdb90c51266261383b/Cografya-Kaderdir-Uezerine-On-the-Geography-is-Destiny-Oez.pdf

https://www.academia.edu/download/51155369/Dunyada_ve_Turkiyede_Yosulluk_Bildirisi.pdf

http://w.solyayinlari.com/pdf/nu_meek.pdf

